"""response_language_id_and_session

Revision ID: 0f6d758d0ebd
Revises: e91556916cb0
Create Date: 2026-05-07 15:18:11.160147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6d758d0ebd'
down_revision: Union[str, Sequence[str], None] = 'e91556916cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dataset_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['unclean_datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dataset_id', 'language_id', name='uq_user_dataset_lang')
    )
    op.drop_constraint(op.f('fk_refresh_tokens_user_id'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_response_votes_user_id'), 'response_votes', type_='foreignkey')
    op.create_foreign_key(None, 'response_votes', 'users', ['user_id'], ['id'])
    op.add_column('responses', sa.Column('language_id', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_user_dataset_language', 'responses', ['user_id', 'dataset_id', 'language_id'])
    op.drop_constraint(op.f('fk_responses_user_id'), 'responses', type_='foreignkey')
    op.create_foreign_key(None, 'responses', 'languages', ['language_id'], ['id'])
    op.create_foreign_key(None, 'responses', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('uq_subtribe_name_tribe', 'subtribes', ['name', 'tribe_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subtribe_name_tribe', 'subtribes', type_='unique')
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_responses_user_id'), 'responses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_dataset_language', 'responses', type_='unique')
    op.drop_column('responses', 'language_id')
    op.drop_constraint(None, 'response_votes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_response_votes_user_id'), 'response_votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_refresh_tokens_user_id'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('user_dataset_sessions')
    # ### end Alembic commands ###
