"""Add AI-generated responses support

Revision ID: 98ab65168833
Revises: 5f66c1f73bbb
Create Date: 2026-05-11 08:29:09.431028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ab65168833'
down_revision: Union[str, Sequence[str], None] = '5f66c1f73bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('is_ai_generated', sa.Boolean(), nullable=False))
    op.alter_column('responses', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('uq_ai_response', 'responses', ['dataset_id', 'language_id', 'category_id'], unique=True, postgresql_where=sa.text('is_ai_generated = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ai_response', table_name='responses', postgresql_where=sa.text('is_ai_generated = true'))
    op.alter_column('responses', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('responses', 'is_ai_generated')
    # ### end Alembic commands ###
