"""Make original_text unique

Revision ID: 9b6cf4bfca2c
Revises: 98ab65168833
Create Date: 2026-05-11 09:56:10.520643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6cf4bfca2c'
down_revision: Union[str, Sequence[str], None] = '98ab65168833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Deduplicate existing original_text entries by appending their ID
    op.execute("""
        WITH duplicates AS (
            SELECT id, original_text,
            ROW_NUMBER() OVER(PARTITION BY original_text ORDER BY created_at) as rn
            FROM unclean_datasets
        )
        UPDATE unclean_datasets
        SET original_text = unclean_datasets.original_text || ' - dup ' || CAST(duplicates.id AS VARCHAR)
        FROM duplicates
        WHERE unclean_datasets.id = duplicates.id AND duplicates.rn > 1;
    """)
    op.create_unique_constraint('uq_unclean_datasets_original_text', 'unclean_datasets', ['original_text'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_unclean_datasets_original_text', 'unclean_datasets', type_='unique')
    # ### end Alembic commands ###
